trigger:
- main
- SettingUpFrontendPipeline 
pool:
  name: Default   # Replace 'Default' with the name of your self-hosted agent pool
  demands:
    - agent.name -equals DESKTOP-HJ6NA99

variables:
  nodeVersion: '22.x'
  buildDir: '$(System.DefaultWorkingDirectory)/.next'
  artifactName: 'drop'

steps:
#Step 1
- checkout: self
  displayName: 'Checkout repository'

#Step 2
- task: UseNode@1
  displayName: 'Use Node.js $(nodeVersion)'
  inputs:
    version: '$(nodeVersion)'

- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    path: $(Pipeline.Workspace)/.npm

#Step 3
- script: npm ci --cache $(Pipeline.Workspace)/.npm --prefer-offline
  displayName: 'Install dependencies with npm ci (cached)'

- task: Cache@2
  inputs:
    key: 'next-build | "$(Agent.OS)" | package-lock.json'
    path: $(Pipeline.Workspace)/.next
    failOnCacheMiss: false
    
#Step 4
- script: npm run build
  displayName: 'Build Next.js project'

#Step 5
- task: PublishBuildArtifacts@1
  displayName: 'Publish frontend build artifacts'
  inputs:
    PathtoPublish: '$(buildDir)'
    ArtifactName: '$(artifactName)'
    publishLocation: 'Container' 


#Step 6
#- task: AzureWebApp@1
#  displayName: 'Deploy Frontend to Azure App Service'
#  inputs:
#    azureSubscription: ''
#    appName: ''
#    package: '$(Build.ArtifactStagingDirectory)/drop'
